controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_app:
    resource: ../src/Controller/Api/
    type: attribute
    prefix: '/v1/api'